package Mernis2;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 6FFCC889DFF8A50D1DC0CBB42A9061000EAA90E3A1CFCDBB7E6BE5F47C1D4EF5E7B8DFC50BAF8DE6E02D49A6DE0FC5E81F6481DC549C4D7676D16456781026CF
//------------------------------------------------------------------------
import java.util.Date;


public interface CTBDateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}